DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;

create table prod_sales 
(
	continent varchar(20),
	country varchar(20),
	city varchar(20),
	units_sold integer
);

INSERT INTO prod_sales (continent, country, city, units_sold)
VALUES

('Australia', 'Ethiopia', 'Wichita', 407),
('North America', 'Eritrea', 'Fresno', 29),
('Europe', 'Chile', 'Wichita', 445),
('South America', 'Djibouti', 'Oakland', 164),
('South America', 'Chad', 'Detroit', 319),
('South America', 'Comoros', 'El Paso', 92),
('Africa', 'Algeria', 'Boston', 308),
('Europe', 'Algeria', 'Jacksonville', 17),
('Europe', 'Bahamas', 'Columbus', 173),
('Europe', 'Guinea', 'Los Angeles', 436),
('Asia', 'China', 'Washington', 214),
('Australia', 'Barbados', 'San Jose', 138),
('South America', 'Estonia', 'Atlanta', 141),
('North America', 'Colombia', 'Memphis', 146),
('Africa', 'Bahamas', 'Milwaukee', 388),
('Asia', 'Afghanistan', 'Baltimore', 156),
('North America', 'Cameroon', 'Portland', 82),
('Europe', 'Armenia', 'Portland', 431),
('South America', 'Azerbaijan', 'Fresno', 253),
('Asia', 'Czech Republic', 'Boston', 24),
('Australia', 'Georgia', 'Seattle', 466),
('Australia', 'Bulgaria', 'Sacramento', 312),
('Asia', 'Angola', 'Albuquerque', 292),
('South America', 'Honduras', 'Charlotte', 369),
('Australia', 'Bolivia', 'Memphis', 240),
('Europe', 'Colombia', 'Memphis', 64),
('Europe', 'Azerbaijan', 'Houston', 232),
('Australia', 'Bolivia', 'Nashville', 178),
('Asia', 'Albania', 'Sacramento', 81),
('Asia', 'Georgia', 'Milwaukee', 62),
('South America', 'Guinea-Bissau', 'Portland', 212),
('North America', 'Cuba', 'Austin', 345),
('North America', 'Cyprus', 'Tucson', 28),
('Australia', 'Germany', 'Atlanta', 231),
('South America', 'Georgia', 'San Jose', 81),
('Asia', 'Bangladesh', 'Tulsa', 297),
('Europe', 'Djibouti', 'Atlanta', 78),
('Asia', 'Antigua and Barbuda', 'Washington', 398),
('Africa', 'Estonia', 'Wichita', 279),
('North America', 'Dominica', 'San Jose', 67),
('South America', 'Dominica', 'Tulsa', 44),
('South America', 'Greece', 'Albuquerque', 274),
('Australia', 'Burundi', 'Raleigh', 366),
('Europe', 'Guyana', 'Detroit', 15),
('North America', 'Cameroon', 'Charlotte', 242),
('North America', 'Cambodia', 'Seattle', 261),
('North America', 'Brunei', 'Baltimore', 37),
('Africa', 'Benin', 'Philadelphia', 271),
('South America', 'Comoros', 'Philadelphia', 41),
('North America', 'Bahamas', 'Los Angeles', 227),
('North America', 'Eritrea', 'Jacksonville', 303),
('Africa', 'Bolivia', 'Tulsa', 55),
('Europe', 'Bolivia', 'Philadelphia', 376),
('Africa', 'Croatia', 'Memphis', 211),
('Africa', 'Dominica', 'Nashville', 34),
('Europe', 'Cuba', 'Tulsa', 283),
('South America', 'China', 'Dallas', 195),
('North America', 'Algeria', 'Fresno', 65),
('North America', 'Gabon', 'Boston', 452),
('South America', 'Albania', 'Memphis', 473),
('Europe', 'Barbados', 'Washington', 75),
('North America', 'Australia', 'New York', 283),
('South America', 'Finland', 'Miami', 124),
('North America', 'Austria', 'Houston', 494),
('North America', 'Czech Republic', 'Seattle', 224),
('Africa', 'Bahamas', 'Memphis', 304),
('Asia', 'Bangladesh', 'Arlington', 162),
('Asia', 'Eritrea', 'Raleigh', 336),
('Africa', 'Ethiopia', 'Philadelphia', 121),
('Asia', 'Cape Verde', 'Philadelphia', 288),
('South America', 'Hungary', 'San Jose', 290),
('Europe', 'Andorra', 'Minneapolis', 438),
('Europe', 'Bangladesh', 'Arlington', 479),
('Australia', 'Brunei', 'Los Angeles', 386),
('Europe', 'Belarus', 'El Paso', 283),
('Africa', 'Bangladesh', 'Portland', 144),
('Asia', 'Bhutan', 'Fresno', 48),
('North America', 'Belgium', 'Miami', 383),
('Asia', 'Georgia', 'Oakland', 376),
('North America', 'Austria', 'Portland', 309),
('Africa', 'Croatia', 'Albuquerque', 169),
('Australia', 'Germany', 'Philadelphia', 247),
('Africa', 'Burundi', 'Louisville', 91),
('Australia', 'Burundi', 'Omaha', 337),
('Europe', 'Bangladesh', 'New York', 236),
('North America', 'Angola', 'Miami', 416),
('North America', 'Azerbaijan', 'Detroit', 369),
('South America', 'Andorra', 'Louisville', 155),
('Asia', 'Greece', 'Detroit', 293),
('Africa', 'Honduras', 'Jacksonville', 179),
('Asia', 'Salvador', 'Dallas', 226),
('Asia', 'Colombia', 'Dallas', 420),
('North America', 'Bahamas', 'Oakland', 51),
('Australia', 'Bulgaria', 'Los Angeles', 343),
('Europe', 'Bhutan', 'San Jose', 58),
('Europe', 'Belarus', 'San Jose', 246),
('South America', 'Brazil', 'Nashville', 255),
('Africa', 'Botswana', 'Houston', 371),
('South America', 'Argentina', 'Wichita', 140),
('Australia', 'Argentina', 'Albuquerque', 248),
('Australia', 'Bahamas', 'Los Angeles', 309),
('South America', 'Brunei', 'Washington', 184),
('South America', 'Afghanistan', 'Los Angeles', 14),
('Europe', 'Benin', 'Nashville', 284),
('Australia', 'Finland', 'Indianapolis', 197),
('Australia', 'Czech Republic', 'Jacksonville', 463),
('Europe', 'Bahrain', 'Milwaukee', 353),
('South America', 'Ecuador', 'Miami', 340),
('Australia', 'Croatia', 'Austin', 470),
('Australia', 'Greece', 'Los Angeles', 148),
('Europe', 'Gambia', 'Oakland', 363),
('Australia', 'Angola', 'Dallas', 323),
('North America', 'Hungary', 'Boston', 59),
('North America', 'Salvador', 'Wichita', 466),
('Africa', 'Cape Verde', 'Austin', 334),
('South America', 'Chad', 'Washington', 385),
('Asia', 'Comoros', 'Minneapolis', 124),
('Africa', 'Austria', 'Austin', 438),
('South America', 'Belarus', 'Jacksonville', 408),
('South America', 'Dominica', 'Charlotte', 164),
('Europe', 'Denmark', 'Sacramento', 496),
('Africa', 'Germany', 'Dallas', 165),
('Europe', 'Gambia', 'Tulsa', 444),
('Europe', 'Andorra', 'Nashville', 47),
('South America', 'Azerbaijan', 'Washington', 183),
('North America', 'Armenia', 'Detroit', 465),
('Europe', 'Guyana', 'Albuquerque', 487),
('South America', 'Guatemala', 'Albuquerque', 81),
('North America', 'Angola', 'San Jose', 393),
('Australia', 'Iceland', 'Omaha', 396),
('North America', 'Bahamas', 'Atlanta', 233),
('Australia', 'Bolivia', 'Louisville', 416),
('Africa', 'Eritrea', 'Albuquerque', 228),
('North America', 'Bahamas', 'Charlotte', 347),
('Europe', 'Albania', 'Denver', 208),
('North America', 'Iceland', 'Jacksonville', 182),
('Africa', 'Cambodia', 'Los Angeles', 27),
('Asia', 'Azerbaijan', 'Baltimore', 460),
('Asia', 'Guyana', 'Phoenix', 279),
('Africa', 'Haiti', 'Seattle', 278),
('Asia', 'China', 'El Paso', 333),
('North America', 'Bolivia', 'Austin', 395),
('Africa', 'Iceland', 'Houston', 188),
('Africa', 'Gambia', 'Memphis', 396),
('Asia', 'Chad', 'Wichita', 170),
('Africa', 'Belize', 'Boston', 392),
('South America', 'Andorra', 'Houston', 62),
('Asia', 'Bulgaria', 'Mesa', 233),
('North America', 'Croatia', 'Atlanta', 240),
('Africa', 'Cambodia', 'Albuquerque', 472),
('Europe', 'Cape Verde', 'Philadelphia', 143),
('Europe', 'Barbados', 'Raleigh', 308),
('Africa', 'China', 'Houston', 239),
('North America', 'Azerbaijan', 'Atlanta', 375),
('Africa', 'Guinea-Bissau', 'Portland', 413),
('Australia', 'Salvador', 'Tulsa', 119),
('Africa', 'Botswana', 'Atlanta', 335),
('Asia', 'Armenia', 'Miami', 480),
('Europe', 'Cyprus', 'Albuquerque', 36),
('Africa', 'Armenia', 'Atlanta', 464),
('Asia', 'Salvador', 'Tucson', 475),
('Europe', 'Botswana', 'Jacksonville', 141),
('Africa', 'Georgia', 'Tucson', 334),
('Asia', 'Bhutan', 'Charlotte', 90),
('Africa', 'Albania', 'New York', 151),
('Europe', 'Grenada', 'Albuquerque', 96),
('Asia', 'Benin', 'Mesa', 81),
('Europe', 'Ghana', 'Mesa', 166),
('Australia', 'Chad', 'Portland', 262),
('Australia', 'Germany', 'Detroit', 143),
('Europe', 'Grenada', 'Philadelphia', 381),
('Australia', 'Hungary', 'Fresno', 190),
('Africa', 'Croatia', 'Louisville', 237),
('North America', 'Greece', 'El Paso', 237),
('Africa', 'Finland', 'Columbus', 168),
('Australia', 'Bhutan', 'Albuquerque', 193),
('South America', 'Australia', 'Raleigh', 316),
('Europe', 'Dominica', 'Nashville', 448),
('Australia', 'Haiti', 'Tucson', 266),
('North America', 'Burundi', 'Nashville', 326),
('Europe', 'Salvador', 'Raleigh', 13),
('South America', 'Cyprus', 'Tucson', 250),
('Europe', 'Austria', 'Washington', 387),
('Australia', 'Chad', 'Houston', 399),
('North America', 'Cyprus', 'Mesa', 76),
('South America', 'Armenia', 'El Paso', 133),
('Asia', 'Georgia', 'Omaha', 192),
('South America', 'Chile', 'Baltimore', 407),
('Africa', 'Cuba', 'Albuquerque', 485),
('Africa', 'Guinea', 'Denver', 376),
('South America', 'Estonia', 'Albuquerque', 42),
('Africa', 'France', 'Austin', 311),
('Africa', 'Iceland', 'Memphis', 57),
('Australia', 'Grenada', 'Tulsa', 155),
('Africa', 'Eritrea', 'Los Angeles', 459),
('North America', 'Ghana', 'Chicago', 236),
('Asia', 'Ghana', 'Fresno', 391),
('Asia', 'Cameroon', 'Portland', 406),
('Asia', 'Ethiopia', 'Wichita', 188),
('Asia', 'Colombia', 'Los Angeles', 84),
('South America', 'Burundi', 'Minneapolis', 430),
('Africa', 'Belize', 'Indianapolis', 12),
('South America', 'Andorra', 'San Jose', 210),
('Australia', 'Brazil', 'Wichita', 202),
('North America', 'Gambia', 'Wichita', 396),
('North America', 'Gambia', 'Omaha', 54),
('Africa', 'Estonia', 'Nashville', 172),
('Europe', 'Germany', 'Oakland', 156),
('Asia', 'Hungary', 'Austin', 97),
('North America', 'Gabon', 'Memphis', 423),
('Australia', 'Denmark', 'Omaha', 219),
('Asia', 'Antigua and Barbuda', 'Oakland', 139),
('Africa', 'Cyprus', 'Nashville', 70),
('Africa', 'Gambia', 'Atlanta', 23),
('Europe', 'Croatia', 'Portland', 408),
('Australia', 'Bahamas', 'Baltimore', 451),
('Africa', 'Cyprus', 'San Jose', 390),
('Asia', 'Eritrea', 'Omaha', 266),
('South America', 'Chad', 'Los Angeles', 19),
('Asia', 'Croatia', 'Mesa', 128),
('Europe', 'Croatia', 'Albuquerque', 61),
('South America', 'Botswana', 'Omaha', 175),
('Europe', 'Cyprus', 'Albuquerque', 48),
('North America', 'Australia', 'Detroit', 424),
('Asia', 'Estonia', 'Austin', 351),
('Africa', 'Iceland', 'Portland', 252),
('South America', 'Benin', 'Austin', 460),
('Europe', 'Fiji', 'Washington', 236),
('Asia', 'Honduras', 'Albuquerque', 412),
('Europe', 'Germany', 'Arlington', 314),
('Asia', 'Hungary', 'Sacramento', 68),
('North America', 'Canada', 'Austin', 148),
('Africa', 'Fiji', 'Minneapolis', 370),
('North America', 'Brazil', 'Raleigh', 480),
('North America', 'Australia', 'Austin', 72),
('Europe', 'Belarus', 'Los Angeles', 238),
('Europe', 'Iceland', 'New York', 427),
('Asia', 'Guinea', 'Philadelphia', 394),
('North America', 'Ethiopia', 'Detroit', 370),
('North America', 'Barbados', 'Phoenix', 11),
('South America', 'Haiti', 'Los Angeles', 439),
('North America', 'Guyana', 'Houston', 94),
('Africa', 'Comoros', 'Mesa', 145),
('South America', 'Brunei', 'Jacksonville', 250),
('Australia', 'Egypt', 'Philadelphia', 455),
('Europe', 'Comoros', 'Phoenix', 413),
('South America', 'Colombia', 'Baltimore', 258),
('Europe', 'Comoros', 'Mesa', 177),
('Asia', 'China', 'Charlotte', 459),
('Asia', 'Egypt', 'Portland', 345),
('Africa', 'Guinea-Bissau', 'Chicago', 145),
('North America', 'Cambodia', 'Tulsa', 338),
('Europe', 'Egypt', 'New York', 262),
('Asia', 'Denmark', 'Mesa', 21),
('Asia', 'Austria', 'Omaha', 451),
('Asia', 'Colombia', 'Memphis', 442),
('Australia', 'China', 'Washington', 93),
('Asia', 'Ethiopia', 'Tucson', 44),
('Africa', 'Dominica', 'Raleigh', 130),
('Europe', 'Croatia', 'Memphis', 280),
('Africa', 'Bolivia', 'Milwaukee', 169),
('North America', 'Albania', 'El Paso', 214),
('Australia', 'Gambia', 'Jacksonville', 41),
('Asia', 'Belarus', 'Phoenix', 452),
('Australia', 'Bolivia', 'Milwaukee', 490),
('Europe', 'Ecuador', 'Detroit', 474),
('Africa', 'Georgia', 'Philadelphia', 203),
('Australia', 'Gabon', 'Memphis', 366),
('South America', 'Bolivia', 'Tulsa', 188),
('Europe', 'Haiti', 'Milwaukee', 258),
('Europe', 'Guyana', 'Seattle', 450),
('Asia', 'Argentina', 'Los Angeles', 248),
('North America', 'Armenia', 'Indianapolis', 380),
('Africa', 'Belize', 'Detroit', 403),
('South America', 'Denmark', 'Tulsa', 99),
('North America', 'Angola', 'Phoenix', 209),
('Africa', 'Cuba', 'Columbus', 361),
('North America', 'Bangladesh', 'Indianapolis', 418),
('Asia', 'Comoros', 'Baltimore', 249),
('Australia', 'Egypt', 'Omaha', 55),
('South America', 'Bulgaria', 'Seattle', 181),
('Australia', 'Georgia', 'Portland', 25),
('Australia', 'Barbados', 'Tucson', 352),
('Australia', 'Andorra', 'Mesa', 34),
('Asia', 'Finland', 'Los Angeles', 86),
('North America', 'Fiji', 'Austin', 475),
('Africa', 'Hungary', 'Albuquerque', 455),
('Europe', 'Australia', 'San Jose', 421),
('Australia', 'Gambia', 'Raleigh', 305),
('Asia', 'Australia', 'Philadelphia', 346),
('Australia', 'Andorra', 'Albuquerque', 50),
('South America', 'Bangladesh', 'Phoenix', 480),
('Asia', 'Croatia', 'Fresno', 327),
('Africa', 'Estonia', 'Indianapolis', 416),
('Australia', 'Albania', 'Baltimore', 76),
('Europe', 'Germany', 'Mesa', 73),
('Australia', 'Germany', 'Mesa', 295),
('Asia', 'Algeria', 'Chicago', 224),
('Europe', 'Guinea-Bissau', 'Phoenix', 128),
('Africa', 'Haiti', 'El Paso', 23),
('North America', 'Cambodia', 'Denver', 183),
('South America', 'Benin', 'Oakland', 160),
('Africa', 'Azerbaijan', 'Baltimore', 43),
('North America', 'Ecuador', 'Seattle', 398),
('Australia', 'Antigua and Barbuda', 'Seattle', 140),
('Asia', 'Ecuador', 'Wichita', 234),
('South America', 'Grenada', 'Oakland', 108),
('South America', 'Comoros', 'Columbus', 222),
('North America', 'Brazil', 'Tucson', 193),
('Africa', 'Finland', 'Arlington', 470),
('Australia', 'Georgia', 'Austin', 325),
('Asia', 'Grenada', 'Fresno', 429),
('Africa', 'Iceland', 'Denver', 53),
('Asia', 'Egypt', 'Louisville', 313),
('South America', 'Comoros', 'Phoenix', 44),
('South America', 'Guinea', 'Washington', 285),
('Australia', 'Algeria', 'Washington', 120),
('Africa', 'Guatemala', 'Arlington', 146),
('North America', 'Cambodia', 'Tulsa', 303),
('Europe', 'Colombia', 'Tucson', 31),
('North America', 'Bulgaria', 'Washington', 348),
('South America', 'Bhutan', 'Memphis', 302),
('Europe', 'Gabon', 'Sacramento', 400),
('North America', 'Bangladesh', 'Philadelphia', 319),
('Australia', 'Finland', 'Chicago', 315),
('Asia', 'Salvador', 'Chicago', 239),
('Africa', 'Belgium', 'Indianapolis', 447),
('Europe', 'Azerbaijan', 'Louisville', 331),
('Europe', 'Eritrea', 'Charlotte', 431),
('South America', 'Brazil', 'Charlotte', 304),
('Africa', 'Belgium', 'New York', 397),
('Africa', 'Brunei', 'Denver', 359),
('Asia', 'Hungary', 'Tucson', 308),
('Asia', 'Guyana', 'Milwaukee', 488),
('South America', 'China', 'Tucson', 105),
('Australia', 'Ethiopia', 'Washington', 361),
('Asia', 'Egypt', 'Denver', 307),
('North America', 'Belize', 'Los Angeles', 93),
('Asia', 'Haiti', 'Milwaukee', 57),
('Asia', 'Guinea-Bissau', 'Arlington', 274),
('Asia', 'Bangladesh', 'Nashville', 421),
('Asia', 'Bangladesh', 'New York', 146),
('South America', 'Eritrea', 'Philadelphia', 119),
('South America', 'Guinea-Bissau', 'Arlington', 56),
('Asia', 'Chad', 'Baltimore', 483),
('Asia', 'Grenada', 'Phoenix', 389),
('Asia', 'Brazil', 'Columbus', 235),
('Asia', 'Guatemala', 'Jacksonville', 341),
('North America', 'Greece', 'Washington', 391),
('Australia', 'Honduras', 'Nashville', 83),
('Australia', 'Djibouti', 'Phoenix', 357),
('South America', 'Barbados', 'Columbus', 360),
('Africa', 'Cape Verde', 'New York', 493),
('North America', 'France', 'Detroit', 125),
('Africa', 'Bahrain', 'Minneapolis', 45),
('South America', 'Bhutan', 'New York', 378),
('Australia', 'Comoros', 'Memphis', 440),
('Europe', 'Greece', 'Seattle', 173),
('North America', 'Australia', 'Oakland', 228),
('North America', 'Iceland', 'Denver', 97),
('North America', 'Haiti', 'Seattle', 214),
('South America', 'Salvador', 'Mesa', 113),
('Europe', 'Guatemala', 'Indianapolis', 218),
('North America', 'Haiti', 'Tucson', 312),
('Asia', 'Brunei', 'Wichita', 14),
('South America', 'Bahamas', 'Minneapolis', 198),
('Australia', 'Botswana', 'Wichita', 37),
('Africa', 'Bangladesh', 'Tulsa', 282),
('South America', 'Chad', 'Seattle', 89),
('North America', 'Botswana', 'Charlotte', 300),
('South America', 'Bahamas', 'Arlington', 64),
('Africa', 'Greece', 'Denver', 339),
('Asia', 'Ethiopia', 'Wichita', 330),
('Asia', 'Georgia', 'Wichita', 209),
('North America', 'Canada', 'New York', 275),
('North America', 'Cape Verde', 'Chicago', 398),
('Australia', 'Afghanistan', 'Denver', 480),
('Europe', 'Cambodia', 'Jacksonville', 170),
('Europe', 'Germany', 'Omaha', 340),
('South America', 'Brunei', 'Jacksonville', 96),
('Australia', 'Dominica', 'Baltimore', 232),
('Europe', 'Belarus', 'Detroit', 160),
('Australia', 'Algeria', 'El Paso', 381),
('Australia', 'Angola', 'Omaha', 397),
('Australia', 'Argentina', 'Houston', 259),
('Africa', 'Burundi', 'Nashville', 496),
('Asia', 'Guatemala', 'Omaha', 213),
('Africa', 'Bahamas', 'Memphis', 154),
('Africa', 'Cyprus', 'San Jose', 279),
('North America', 'Cuba', 'Baltimore', 453),
('Europe', 'Burundi', 'Boston', 137),
('Europe', 'Czech Republic', 'Nashville', 97),
('South America', 'Brunei', 'Sacramento', 275),
('Africa', 'Honduras', 'Mesa', 383),
('Africa', 'Bulgaria', 'Fresno', 355),
('North America', 'Egypt', 'Tulsa', 499),
('Europe', 'France', 'Miami', 445),
('North America', 'Austria', 'Chicago', 53),
('Africa', 'Cameroon', 'Minneapolis', 256),
('Africa', 'Argentina', 'Detroit', 358),
('Australia', 'Benin', 'Dallas', 179),
('North America', 'Bahamas', 'Denver', 497),
('Africa', 'Bangladesh', 'Baltimore', 168),
('North America', 'Chile', 'Wichita', 495),
('Africa', 'Djibouti', 'New York', 56),
('South America', 'Fiji', 'Jacksonville', 38),
('North America', 'Eritrea', 'Atlanta', 133),
('Australia', 'Denmark', 'Boston', 178),
('Australia', 'Finland', 'Columbus', 186),
('North America', 'Guatemala', 'Boston', 206),
('Australia', 'Djibouti', 'Columbus', 201),
('South America', 'Chad', 'Albuquerque', 127),
('Europe', 'Bhutan', 'Jacksonville', 244),
('Asia', 'Cambodia', 'Mesa', 386),
('Africa', 'Hungary', 'Wichita', 487),
('South America', 'Cameroon', 'Dallas', 192),
('Africa', 'Canada', 'Albuquerque', 58),
('North America', 'Ethiopia', 'Columbus', 308),
('Africa', 'Germany', 'Los Angeles', 102),
('Europe', 'Chile', 'Tulsa', 22),
('South America', 'Australia', 'Louisville', 352),
('Australia', 'Gambia', 'Philadelphia', 51),
('Asia', 'France', 'Tucson', 273),
('Australia', 'Salvador', 'Memphis', 106),
('North America', 'Brazil', 'Louisville', 263),
('Australia', 'Guinea-Bissau', 'Baltimore', 178),
('South America', 'Chad', 'Portland', 446),
('Europe', 'Belarus', 'Fresno', 467),
('Europe', 'Iceland', 'Washington', 190),
('Australia', 'France', 'Baltimore', 342),
('Australia', 'Germany', 'Indianapolis', 279),
('North America', 'Honduras', 'Chicago', 360),
('Africa', 'Bahamas', 'Houston', 198),
('North America', 'Denmark', 'Boston', 219),
('Australia', 'Georgia', 'Austin', 482),
('Australia', 'Chile', 'Columbus', 401),
('South America', 'Benin', 'Sacramento', 276),
('Africa', 'Djibouti', 'Albuquerque', 461),
('Europe', 'Czech Republic', 'Portland', 381),
('South America', 'Ethiopia', 'Mesa', 240),
('North America', 'Bangladesh', 'Denver', 267),
('South America', 'Brunei', 'Memphis', 475),
('Europe', 'Ethiopia', 'Louisville', 329),
('Asia', 'Greece', 'Minneapolis', 420),
('Africa', 'Barbados', 'Oakland', 178),
('North America', 'Dominica', 'Milwaukee', 275),
('Africa', 'Bahamas', 'Omaha', 260),
('Asia', 'Gabon', 'Mesa', 88),
('South America', 'Cyprus', 'Philadelphia', 350),
('Asia', 'Gambia', 'Nashville', 451),
('Australia', 'Honduras', 'Omaha', 238),
('North America', 'Angola', 'Houston', 163),
('North America', 'Bolivia', 'Tulsa', 131),
('North America', 'Brazil', 'Miami', 401),
('South America', 'Dominica', 'Louisville', 389),
('North America', 'Belarus', 'El Paso', 87),
('Europe', 'Haiti', 'Portland', 57),
('South America', 'Chad', 'Oakland', 228),
('North America', 'Guyana', 'Baltimore', 184),
('North America', 'Belgium', 'Portland', 186),
('North America', 'Gabon', 'Philadelphia', 464),
('Europe', 'Iceland', 'Phoenix', 71),
('Africa', 'Comoros', 'San Jose', 431),
('Africa', 'Gambia', 'Chicago', 476),
('Asia', 'Gabon', 'Columbus', 402),
('Australia', 'Gabon', 'Detroit', 31),
('Africa', 'Belgium', 'Austin', 381),
('Europe', 'Comoros', 'Arlington', 105),
('Europe', 'Comoros', 'San Jose', 259),
('South America', 'Fiji', 'Tucson', 37),
('Asia', 'Salvador', 'Detroit', 204),
('South America', 'Salvador', 'Austin', 323),
('Australia', 'France', 'Raleigh', 240),
('South America', 'Benin', 'Washington', 116),
('Europe', 'Bahrain', 'Memphis', 386),
('Asia', 'Algeria', 'Austin', 111),
('Australia', 'Guinea', 'Detroit', 486),
('Australia', 'Fiji', 'Jacksonville', 338),
('North America', 'Armenia', 'Detroit', 222),
('Asia', 'Cameroon', 'Charlotte', 317),
('Asia', 'Grenada', 'Austin', 107),
('Asia', 'Germany', 'Portland', 110),
('Asia', 'Benin', 'Memphis', 379),
('North America', 'Albania', 'Detroit', 220),
('Europe', 'Cyprus', 'Tucson', 81),
('South America', 'Armenia', 'Memphis', 135),
('Europe', 'Chad', 'Boston', 12),
('South America', 'Algeria', 'New York', 31),
('Australia', 'Cyprus', 'Tucson', 230),
('Europe', 'Cuba', 'Columbus', 184),
('North America', 'China', 'San Jose', 291),
('Asia', 'Bangladesh', 'Austin', 58),
('Africa', 'Algeria', 'Indianapolis', 238),
('Asia', 'Ecuador', 'Detroit', 490),
('Asia', 'Angola', 'Phoenix', 113),
('South America', 'Bhutan', 'Columbus', 128),
('Asia', 'Burundi', 'Nashville', 56),
('Africa', 'Chad', 'Austin', 269),
('North America', 'Ghana', 'Albuquerque', 38),
('North America', 'Argentina', 'Washington', 498),
('Australia', 'Brunei', 'Portland', 447),
('Australia', 'Afghanistan', 'Austin', 208),
('North America', 'Angola', 'New York', 272),
('Asia', 'Ecuador', 'Philadelphia', 332),
('North America', 'Bulgaria', 'Milwaukee', 173),
('Africa', 'Ecuador', 'Phoenix', 178),
('South America', 'Denmark', 'Miami', 132),
('Europe', 'Dominica', 'Washington', 38),
('South America', 'Algeria', 'Seattle', 61),
('Africa', 'Ethiopia', 'Fresno', 80),
('Asia', 'Guyana', 'Wichita', 265),
('Europe', 'Argentina', 'Raleigh', 279),
('Australia', 'Botswana', 'Raleigh', 427),
('Australia', 'Haiti', 'Baltimore', 137),
('Europe', 'Bangladesh', 'San Jose', 329),
('Asia', 'Austria', 'Seattle', 352),
('North America', 'Chile', 'Nashville', 473),
('Asia', 'Bahrain', 'Seattle', 479),
('Europe', 'Australia', 'Phoenix', 120),
('North America', 'Bahrain', 'Chicago', 242),
('Europe', 'Antigua and Barbuda', 'Philadelphia', 202),
('North America', 'Bahrain', 'Philadelphia', 399),
('Australia', 'Cuba', 'Austin', 51),
('North America', 'Bahamas', 'Albuquerque', 249),
('South America', 'Germany', 'Austin', 476),
('North America', 'Gambia', 'Charlotte', 136),
('South America', 'Guatemala', 'Atlanta', 240),
('Africa', 'Belgium', 'Baltimore', 211),
('South America', 'Estonia', 'Oakland', 272),
('North America', 'Bhutan', 'Milwaukee', 52),
('Australia', 'Bhutan', 'Philadelphia', 488),
('Australia', 'Greece', 'Miami', 436),
('Australia', 'Djibouti', 'Wichita', 364),
('North America', 'France', 'Minneapolis', 216),
('Australia', 'Ethiopia', 'Charlotte', 39),
('Africa', 'Gabon', 'Washington', 240),
('South America', 'Fiji', 'Detroit', 188),
('South America', 'Comoros', 'Arlington', 429),
('Europe', 'Greece', 'Arlington', 484),
('North America', 'Andorra', 'Milwaukee', 391),
('North America', 'Haiti', 'Tucson', 287),
('Europe', 'Bulgaria', 'Oakland', 89),
('Europe', 'Australia', 'Jacksonville', 364),
('Africa', 'Djibouti', 'Columbus', 232),
('South America', 'Guinea', 'Phoenix', 404),
('South America', 'Estonia', 'San Jose', 161),
('Africa', 'China', 'Tulsa', 118),
('Asia', 'Cape Verde', 'Detroit', 136),
('Europe', 'Barbados', 'Omaha', 413),
('South America', 'Ethiopia', 'Baltimore', 255),
('North America', 'China', 'Milwaukee', 434),
('North America', 'Albania', 'Omaha', 342),
('Africa', 'Albania', 'Chicago', 172),
('Australia', 'Greece', 'Oakland', 217),
('Africa', 'Cuba', 'Louisville', 114),
('South America', 'Brazil', 'Philadelphia', 225),
('North America', 'Eritrea', 'Mesa', 256),
('Asia', 'Ghana', 'Sacramento', 155),
('Africa', 'Iceland', 'Baltimore', 363),
('Africa', 'Bangladesh', 'Dallas', 442),
('Europe', 'Canada', 'Arlington', 36),
('Africa', 'Hungary', 'Memphis', 122),
('South America', 'Comoros', 'Columbus', 117),
('Europe', 'Grenada', 'Raleigh', 31),
('Europe', 'Ecuador', 'Charlotte', 80),
('Europe', 'Guatemala', 'Denver', 481),
('North America', 'Djibouti', 'Boston', 86),
('Africa', 'Bhutan', 'Oakland', 18),
('South America', 'Brazil', 'Columbus', 50),
('North America', 'Canada', 'Portland', 360),
('Asia', 'Canada', 'Jacksonville', 419),
('Asia', 'Guyana', 'Arlington', 440),
('Africa', 'Bahamas', 'Wichita', 145),
('Australia', 'Belarus', 'Portland', 154),
('Africa', 'Armenia', 'San Jose', 225),
('Asia', 'Djibouti', 'Charlotte', 200),
('North America', 'Colombia', 'Baltimore', 351),
('Europe', 'Belarus', 'Los Angeles', 476),
('Africa', 'Benin', 'Houston', 101),
('Africa', 'Albania', 'Minneapolis', 419),
('Africa', 'Dominica', 'Indianapolis', 76),
('Africa', 'Haiti', 'Los Angeles', 91),
('Africa', 'Croatia', 'Dallas', 139),
('Australia', 'Cambodia', 'Seattle', 310),
('North America', 'Salvador', 'Dallas', 430),
('North America', 'Bhutan', 'Detroit', 360),
('Australia', 'Honduras', 'El Paso', 368),
('Asia', 'Greece', 'San Jose', 388),
('North America', 'Afghanistan', 'Dallas', 202),
('South America', 'Gabon', 'Fresno', 197),
('North America', 'Estonia', 'Washington', 293),
('South America', 'Bangladesh', 'Miami', 355),
('Africa', 'Germany', 'Atlanta', 430),
('North America', 'Guinea', 'Detroit', 21),
('Africa', 'Bahamas', 'Minneapolis', 96),
('Europe', 'Angola', 'Milwaukee', 274),
('Africa', 'Argentina', 'San Jose', 11),
('Europe', 'Bulgaria', 'Tulsa', 81),
('Australia', 'Guyana', 'San Jose', 468),
('Asia', 'Bahamas', 'Tucson', 99),
('Africa', 'Botswana', 'Columbus', 226),
('Australia', 'Czech Republic', 'Austin', 246),
('Africa', 'Estonia', 'Chicago', 155),
('South America', 'Algeria', 'Austin', 82),
('South America', 'China', 'New York', 148),
('Africa', 'Bolivia', 'Washington', 274),
('North America', 'Finland', 'Oakland', 433),
('Africa', 'Guinea-Bissau', 'New York', 276),
('Europe', 'Antigua and Barbuda', 'Dallas', 467),
('Asia', 'Benin', 'Minneapolis', 324),
('Asia', 'Cape Verde', 'Miami', 375),
('Europe', 'Guinea-Bissau', 'Fresno', 379),
('Europe', 'Bolivia', 'Raleigh', 228),
('Australia', 'Colombia', 'Detroit', 280),
('Australia', 'Guatemala', 'Oakland', 402),
('North America', 'Eritrea', 'Mesa', 97),
('Asia', 'Ghana', 'Jacksonville', 492),
('Europe', 'Salvador', 'Wichita', 404),
('North America', 'Chad', 'Los Angeles', 438),
('Europe', 'Bangladesh', 'Baltimore', 300),
('Africa', 'Austria', 'Tulsa', 170),
('Australia', 'Antigua and Barbuda', 'Columbus', 191),
('South America', 'Cameroon', 'Omaha', 434),
('North America', 'Azerbaijan', 'Austin', 472),
('Asia', 'Antigua and Barbuda', 'Indianapolis', 301),
('North America', 'Botswana', 'Raleigh', 272),
('Africa', 'Belarus', 'Seattle', 456),
('North America', 'Brazil', 'Omaha', 204),
('Africa', 'Burundi', 'Tulsa', 94),
('North America', 'Denmark', 'Tulsa', 385),
('Africa', 'Cambodia', 'Columbus', 416),
('Asia', 'Armenia', 'San Jose', 100),
('Africa', 'Bolivia', 'Detroit', 406),
('Europe', 'Albania', 'Boston', 17),
('Asia', 'Belize', 'Portland', 369),
('North America', 'Bahamas', 'Fresno', 361),
('South America', 'Afghanistan', 'Minneapolis', 60),
('Africa', 'Djibouti', 'Philadelphia', 310),
('Africa', 'Hungary', 'Minneapolis', 486),
('North America', 'Cyprus', 'Phoenix', 216),
('Africa', 'Bahamas', 'Los Angeles', 290),
('South America', 'Denmark', 'Mesa', 215),
('Australia', 'Ethiopia', 'Philadelphia', 169),
('Africa', 'Armenia', 'Raleigh', 160),
('Asia', 'Ghana', 'Tucson', 116),
('Asia', 'Chad', 'Phoenix', 288),
('Europe', 'Bahrain', 'Dallas', 244),
('Asia', 'Guyana', 'Dallas', 123),
('South America', 'Brunei', 'Charlotte', 282),
('Australia', 'Egypt', 'Washington', 245),
('Asia', 'Haiti', 'Sacramento', 313),
('North America', 'Iceland', 'Tulsa', 167),
('Europe', 'Germany', 'Boston', 208),
('Asia', 'Guyana', 'Fresno', 178),
('Africa', 'Antigua and Barbuda', 'Sacramento', 415),
('South America', 'Bangladesh', 'Raleigh', 383),
('Australia', 'Guinea-Bissau', 'Tulsa', 266),
('Australia', 'Cape Verde', 'Milwaukee', 177),
('Asia', 'Egypt', 'Denver', 422),
('Africa', 'Austria', 'Fresno', 123),
('North America', 'Denmark', 'Sacramento', 192),
('Europe', 'Angola', 'Sacramento', 235),
('North America', 'Angola', 'Fresno', 21),
('South America', 'China', 'Memphis', 401),
('Europe', 'Argentina', 'Chicago', 178),
('Africa', 'Comoros', 'Philadelphia', 37),
('South America', 'Comoros', 'Omaha', 439),
('North America', 'Antigua and Barbuda', 'Dallas', 320),
('Europe', 'Bangladesh', 'Indianapolis', 434),
('North America', 'Georgia', 'Omaha', 460),
('Asia', 'Denmark', 'Detroit', 324),
('Africa', 'Albania', 'Albuquerque', 184),
('Europe', 'Germany', 'Mesa', 172),
('North America', 'Eritrea', 'Tulsa', 278),
('Australia', 'Chad', 'Dallas', 77),
('Africa', 'Belarus', 'Columbus', 285),
('North America', 'Eritrea', 'Memphis', 317),
('South America', 'Cyprus', 'Portland', 385),
('North America', 'Cuba', 'Phoenix', 105),
('Asia', 'Hungary', 'Omaha', 345),
('Europe', 'Albania', 'Houston', 44),
('Australia', 'Bulgaria', 'Phoenix', 210),
('Europe', 'Bhutan', 'Mesa', 68),
('North America', 'Ghana', 'Wichita', 382),
('North America', 'Cameroon', 'Dallas', 308),
('Africa', 'Bolivia', 'Wichita', 480),
('North America', 'Iceland', 'Oakland', 249),
('Australia', 'Guinea', 'Oakland', 322),
('Asia', 'Albania', 'Miami', 81),
('Asia', 'Bahrain', 'Phoenix', 102),
('Europe', 'Gambia', 'Louisville', 483),
('South America', 'China', 'Nashville', 248),
('Australia', 'Argentina', 'Minneapolis', 205),
('Asia', 'Chile', 'Arlington', 85),
('Africa', 'Ecuador', 'Baltimore', 265),
('South America', 'Guinea-Bissau', 'Arlington', 189),
('Asia', 'Cameroon', 'Arlington', 329),
('Africa', 'Albania', 'Columbus', 270),
('Asia', 'France', 'Chicago', 471),
('South America', 'Belize', 'Columbus', 276),
('Africa', 'Dominica', 'Mesa', 222),
('Australia', 'Ecuador', 'Dallas', 245),
('South America', 'Cuba', 'Baltimore', 307),
('Africa', 'France', 'Los Angeles', 326),
('South America', 'Antigua and Barbuda', 'Chicago', 318),
('Europe', 'Guinea-Bissau', 'Los Angeles', 30),
('Asia', 'Haiti', 'Milwaukee', 470),
('Australia', 'Hungary', 'Oakland', 257),
('Europe', 'Salvador', 'Oakland', 455),
('South America', 'Ethiopia', 'Atlanta', 23),
('Australia', 'Grenada', 'Fresno', 367),
('North America', 'Djibouti', 'Minneapolis', 98),
('Africa', 'Denmark', 'Milwaukee', 396),
('Africa', 'Chad', 'Indianapolis', 69),
('Africa', 'Finland', 'Washington', 61),
('North America', 'Burundi', 'Milwaukee', 299),
('Africa', 'Cameroon', 'New York', 255),
('South America', 'Chad', 'Portland', 199),
('South America', 'Czech Republic', 'Mesa', 50),
('South America', 'Guinea-Bissau', 'Columbus', 424),
('Australia', 'Austria', 'Tulsa', 335),
('Europe', 'Afghanistan', 'Charlotte', 167),
('Europe', 'Chile', 'Oakland', 96),
('Africa', 'Argentina', 'Detroit', 279),
('Europe', 'Djibouti', 'Wichita', 118),
('Asia', 'Salvador', 'Milwaukee', 474),
('Asia', 'Finland', 'Jacksonville', 496),
('North America', 'Guatemala', 'Raleigh', 172),
('Asia', 'Cyprus', 'Houston', 127),
('Asia', 'Albania', 'Oakland', 39),
('Africa', 'Austria', 'Indianapolis', 116),
('North America', 'Barbados', 'Tulsa', 485),
('Australia', 'Ghana', 'Portland', 444),
('Europe', 'Salvador', 'Seattle', 221),
('Europe', 'Czech Republic', 'Omaha', 450),
('Australia', 'Botswana', 'Washington', 338),
('Australia', 'Andorra', 'Chicago', 303),
('South America', 'Brunei', 'Denver', 316),
('Asia', 'Iceland', 'Mesa', 79),
('Asia', 'Bolivia', 'Sacramento', 495),
('Australia', 'Haiti', 'Albuquerque', 157),
('Australia', 'Georgia', 'Baltimore', 180),
('South America', 'Austria', 'Portland', 429),
('South America', 'Georgia', 'El Paso', 326),
('North America', 'Australia', 'New York', 47),
('Europe', 'Ecuador', 'Memphis', 326),
('Asia', 'Hungary', 'Detroit', 19),
('South America', 'Colombia', 'Denver', 389),
('Asia', 'Eritrea', 'San Jose', 483),
('South America', 'Bhutan', 'Los Angeles', 255),
('South America', 'Czech Republic', 'Nashville', 186),
('Europe', 'Angola', 'Charlotte', 440),
('Asia', 'Albania', 'Minneapolis', 493),
('South America', 'Honduras', 'Boston', 430),
('South America', 'Cape Verde', 'Sacramento', 335),
('Australia', 'Benin', 'Austin', 130),
('Europe', 'Dominica', 'Raleigh', 408),
('Australia', 'Hungary', 'San Jose', 302),
('Asia', 'Comoros', 'Minneapolis', 305),
('North America', 'Belarus', 'San Jose', 57),
('Africa', 'Gabon', 'Houston', 181),
('Africa', 'Finland', 'Tucson', 205),
('Australia', 'Guinea-Bissau', 'Louisville', 167),
('South America', 'Botswana', 'Austin', 58),
('North America', 'China', 'Dallas', 293),
('Europe', 'Algeria', 'Miami', 180),
('Europe', 'Belize', 'Indianapolis', 498),
('Australia', 'Ghana', 'Portland', 10),
('Africa', 'Fiji', 'Jacksonville', 29),
('Asia', 'Dominica', 'Oakland', 364),
('Africa', 'Guinea-Bissau', 'Milwaukee', 373),
('Africa', 'Argentina', 'Memphis', 70),
('Asia', 'Angola', 'Fresno', 394),
('South America', 'Brunei', 'Tulsa', 460),
('Asia', 'France', 'Tulsa', 184),
('Asia', 'Albania', 'Austin', 111),
('Asia', 'Haiti', 'Wichita', 337),
('South America', 'Guatemala', 'Detroit', 410),
('Australia', 'Estonia', 'Omaha', 424),
('Asia', 'Egypt', 'Jacksonville', 331),
('Africa', 'Iceland', 'Portland', 456),
('South America', 'Comoros', 'Arlington', 435),
('South America', 'France', 'Charlotte', 212),
('North America', 'Albania', 'Dallas', 172),
('Asia', 'China', 'Detroit', 75),
('Africa', 'Colombia', 'Wichita', 90),
('Europe', 'Bangladesh', 'Fresno', 128),
('Asia', 'Chad', 'Seattle', 136),
('Africa', 'Bahamas', 'Fresno', 230),
('South America', 'Australia', 'Albuquerque', 478),
('Asia', 'Belize', 'Milwaukee', 266),
('Europe', 'Ghana', 'Baltimore', 34),
('Europe', 'Guinea-Bissau', 'Chicago', 166),
('Australia', 'Salvador', 'Wichita', 439),
('Asia', 'Afghanistan', 'Seattle', 165),
('North America', 'France', 'Sacramento', 417),
('North America', 'Estonia', 'Baltimore', 199),
('Europe', 'Afghanistan', 'Washington', 17),
('Europe', 'Angola', 'Austin', 39),
('Australia', 'Guinea', 'San Jose', 304),
('Europe', 'Dominica', 'Jacksonville', 425),
('South America', 'Egypt', 'San Jose', 374),
('Africa', 'Guyana', 'Wichita', 35),
('South America', 'Czech Republic', 'New York', 162),
('Africa', 'Antigua and Barbuda', 'Austin', 95),
('Africa', 'Denmark', 'Sacramento', 285),
('Europe', 'Comoros', 'Austin', 60),
('Europe', 'Iceland', 'Los Angeles', 100),
('Asia', 'Cambodia', 'Baltimore', 132),
('Europe', 'Egypt', 'Columbus', 475),
('Australia', 'Czech Republic', 'Tucson', 78),
('North America', 'Bahamas', 'Phoenix', 54),
('North America', 'Comoros', 'Jacksonville', 278),
('Europe', 'Comoros', 'Memphis', 387),
('Europe', 'Cambodia', 'Los Angeles', 231),
('Australia', 'Gambia', 'Austin', 425),
('Africa', 'Bahrain', 'Miami', 355),
('Africa', 'Greece', 'Atlanta', 440),
('North America', 'Denmark', 'Fresno', 405),
('Australia', 'Algeria', 'Seattle', 23),
('Africa', 'Antigua and Barbuda', 'Portland', 77),
('North America', 'Brazil', 'Detroit', 335),
('Asia', 'Guinea-Bissau', 'Portland', 22),
('North America', 'Albania', 'Minneapolis', 420),
('South America', 'Cape Verde', 'Omaha', 421),
('Africa', 'Brunei', 'Austin', 67),
('South America', 'Bulgaria', 'Columbus', 361),
('Africa', 'Bhutan', 'Charlotte', 385),
('Asia', 'Comoros', 'Charlotte', 233),
('Australia', 'Angola', 'Detroit', 152),
('Asia', 'Guinea', 'Portland', 404),
('North America', 'Bahrain', 'Boston', 98),
('Australia', 'Chad', 'Tucson', 43),
('Asia', 'Salvador', 'Austin', 424),
('Asia', 'Azerbaijan', 'Detroit', 305),
('Asia', 'China', 'Columbus', 340),
('Asia', 'Brazil', 'Detroit', 242),
('North America', 'Antigua and Barbuda', 'Raleigh', 359),
('Europe', 'Austria', 'Louisville', 135),
('Europe', 'Fiji', 'Charlotte', 500),
('Africa', 'Brazil', 'Baltimore', 294),
('Asia', 'Belgium', 'Phoenix', 245),
('Asia', 'Cyprus', 'Sacramento', 85),
('Australia', 'Cuba', 'Milwaukee', 486),
('Asia', 'Canada', 'Mesa', 120),
('North America', 'Grenada', 'Philadelphia', 251),
('Australia', 'Armenia', 'Memphis', 481),
('Australia', 'Albania', 'Charlotte', 292),
('Africa', 'Colombia', 'New York', 124),
('North America', 'Afghanistan', 'Milwaukee', 472),
('Africa', 'Egypt', 'El Paso', 97),
('Africa', 'Croatia', 'Denver', 183),
('Europe', 'Fiji', 'Houston', 55),
('Africa', 'Ecuador', 'El Paso', 380),
('South America', 'Djibouti', 'Tucson', 238),
('North America', 'Denmark', 'Philadelphia', 429),
('South America', 'France', 'Charlotte', 275),
('South America', 'Honduras', 'Baltimore', 128),
('South America', 'Gabon', 'San Jose', 258),
('Africa', 'Denmark', 'Boston', 411),
('Europe', 'Colombia', 'New York', 68),
('Africa', 'Belize', 'Jacksonville', 145),
('Africa', 'Gambia', 'Louisville', 273),
('South America', 'Algeria', 'Tulsa', 463),
('Europe', 'Gabon', 'Memphis', 437),
('North America', 'Guyana', 'Tucson', 232),
('Europe', 'Fiji', 'Nashville', 15),
('Europe', 'Cyprus', 'Chicago', 142),
('Africa', 'Armenia', 'Atlanta', 89),
('Africa', 'Cape Verde', 'Fresno', 334),
('South America', 'Georgia', 'Atlanta', 388),
('Australia', 'Croatia', 'Fresno', 372),
('Africa', 'Benin', 'Raleigh', 477),
('Europe', 'Croatia', 'Chicago', 69),
('Europe', 'Bahamas', 'Nashville', 316),
('Australia', 'Brazil', 'Boston', 271),
('South America', 'Afghanistan', 'Portland', 329),
('Australia', 'Australia', 'Washington', 238),
('Europe', 'Canada', 'Miami', 472),
('Africa', 'Colombia', 'Charlotte', 459),
('South America', 'Afghanistan', 'Wichita', 260),
('Europe', 'Iceland', 'Atlanta', 118),
('North America', 'Cyprus', 'Sacramento', 451),
('North America', 'Czech Republic', 'Minneapolis', 496),
('Africa', 'Azerbaijan', 'Albuquerque', 178),
('Africa', 'Argentina', 'Austin', 290),
('Africa', 'Bhutan', 'Arlington', 287),
('Australia', 'Guinea', 'Columbus', 230),
('Asia', 'Albania', 'Dallas', 294),
('Africa', 'Belize', 'Houston', 157),
('Asia', 'Czech Republic', 'Austin', 88),
('South America', 'Djibouti', 'San Jose', 137),
('Australia', 'Burundi', 'Washington', 87),
('Africa', 'Andorra', 'New York', 333),
('Europe', 'Bahrain', 'Fresno', 14),
('North America', 'Brunei', 'San Jose', 118),
('Australia', 'China', 'Oakland', 444),
('Europe', 'Djibouti', 'Columbus', 271),
('South America', 'Albania', 'San Jose', 493),
('Europe', 'Cameroon', 'Memphis', 440),
('Asia', 'Bangladesh', 'Minneapolis', 409),
('South America', 'Barbados', 'Wichita', 287),
('Australia', 'Australia', 'Denver', 130),
('Asia', 'Estonia', 'Austin', 240),
('Asia', 'Antigua and Barbuda', 'Indianapolis', 403),
('North America', 'Denmark', 'Denver', 198),
('North America', 'Dominica', 'Arlington', 200),
('Europe', 'Armenia', 'Milwaukee', 356),
('Asia', 'Australia', 'Omaha', 82),
('North America', 'Cape Verde', 'Los Angeles', 223),
('Asia', 'Cape Verde', 'Louisville', 333),
('South America', 'Algeria', 'Baltimore', 97),
('Europe', 'Cyprus', 'Albuquerque', 204),
('South America', 'Belize', 'Seattle', 240),
('Africa', 'Cyprus', 'Boston', 120),
('Europe', 'Belize', 'Arlington', 200),
('Europe', 'Guinea', 'Chicago', 391),
('South America', 'Chad', 'Jacksonville', 409),
('North America', 'Croatia', 'Denver', 142),
('Africa', 'Hungary', 'Tucson', 367),
('Europe', 'Azerbaijan', 'Atlanta', 20),
('Asia', 'Angola', 'San Jose', 36),
('Asia', 'Honduras', 'Phoenix', 321),
('Australia', 'Salvador', 'Jacksonville', 405),
('Asia', 'China', 'Seattle', 58),
('South America', 'Fiji', 'New York', 447),
('Asia', 'Croatia', 'Tulsa', 37),
('Asia', 'China', 'Houston', 462),
('Africa', 'Azerbaijan', 'Minneapolis', 313),
('Europe', 'Brunei', 'Miami', 15),
('Africa', 'Australia', 'Phoenix', 77),
('Europe', 'Burundi', 'Raleigh', 424),
('Europe', 'France', 'Dallas', 498),
('South America', 'Comoros', 'Houston', 280),
('Africa', 'Gambia', 'Milwaukee', 485),
('Australia', 'Bangladesh', 'Tucson', 363),
('South America', 'Hungary', 'Dallas', 406),
('Africa', 'Eritrea', 'Austin', 85),
('Africa', 'Brazil', 'Albuquerque', 405),
('Africa', 'Haiti', 'Omaha', 115),
('Africa', 'Antigua and Barbuda', 'Washington', 383),
('Africa', 'Chile', 'Houston', 320),
('South America', 'Barbados', 'Los Angeles', 349),
('Africa', 'Botswana', 'San Jose', 61),
('Europe', 'Eritrea', 'Tulsa', 308),
('North America', 'Finland', 'Arlington', 127),
('Australia', 'Greece', 'Indianapolis', 119),
('Europe', 'Egypt', 'Baltimore', 306),
('Australia', 'Guinea', 'Mesa', 132),
('Europe', 'Bulgaria', 'Tulsa', 101)

-- Built In CUBE Operator
SET STATISTICS TIME ON;

SELECT continent, country, city, SUM(units_sold) AS total_sold
FROM prod_sales
GROUP BY CUBE(continent, country, city)
order by city;

SET STATISTICS TIME OFF;

set statistics time on;
select * from prod_sales
where city='Chicago'
SET STATISTICS TIME OFF;



-- Manually implemented CUBE Operator
SET STATISTICS TIME ON;

SELECT NULL AS continent, NULL AS country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY city 

UNION ALL

SELECT NULL AS continent, country, NULL AS city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY country

UNION ALL

SELECT continent, NULL AS country, NULL AS city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY continent

UNION ALL

SELECT continent, NULL AS country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY continent, city 

UNION ALL

SELECT continent, country, NULL AS city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY continent, country 

UNION ALL

SELECT NULL AS continent, country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY country, city

UNION ALL

SELECT continent, country, city, sum(units_sold) as units_sold
FROM prod_sales
GROUP BY continent, country, city;

SET STATISTICS TIME OFF;

set statistics time on;
select * from prod_sales
where city='Chicago'
set statistics time off;



-- create a view of sales cube 
drop view sales_cube_view;
drop view cube_view;

-- BUILTIN CUBE VIEW

SET STATISTICS TIME ON;
GO
CREATE VIEW cube_view AS
SELECT continent, country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY cube(continent, country, city);
GO
set statistics time off;

-- MANUAL CUBE VIEW

SET STATISTICS TIME ON;
GO
CREATE VIEW sales_cube_view AS
SELECT continent, country, city, SUM(units_sold) AS total_units_sold
FROM (
    
	SELECT NULL AS continent, NULL AS country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY city 

UNION ALL

SELECT NULL AS continent, country, NULL AS city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY country

UNION ALL

SELECT continent, NULL AS country, NULL AS city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY continent

UNION ALL

SELECT continent, NULL AS country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY continent, city 

UNION ALL

SELECT continent, country, NULL AS city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY continent, country 

UNION ALL

SELECT NULL AS continent, country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY country, city

UNION ALL

SELECT continent, country, city, sum(units_sold) as units_sold
FROM prod_sales
GROUP BY continent, country, city


) AS t
GROUP BY continent, country, city;
GO
set statistics time off;



set statistics time on;
select city from sales_cube_view where continent='Asia';
set statistics time off;





-- Another

SET STATISTICS TIME ON;

select continent, country, city, sum(units_sold) as total_sold 
from prod_sales
group by grouping sets((continent, country, city),(continent, country), (continent, city),(country, city), (continent), (country), (city), ());

SET STATISTICS TIME OFF;

set statistics time on;
select * from prod_sales
where city='Chicago'
set statistics time off;


SELECT continent, country, city, SUM(units_sold) AS units_sold
FROM prod_sales
GROUP BY ROLLUP(continent, country, city);
